max-ldap (0.16)   * max-control: Add notify support with sudo max-ldap (0.15)   * Redirect messages to stderr max-ldap (0.14)   * Add acpi=force reboot=warn in extlinux   * Check if extlinux is installed max-ldap (0.13)   * Update 50_extlinux to detect ext4 filesystems   * Depend on new package extlinux-ext4
git-svn-id: http://max.educa.madrid.org:8000/svn/trunk@689 424cea3e-0240-0410-9575-8bd47b58cd33

diff --git a/max-ldap/50_extlinux b/max-ldap/50_extlinux
--- a/max-ldap/50_extlinux
+++ b/max-ldap/50_extlinux
@@ -1,17 +1,26 @@
-#!/bin/sh
+#!/bin/bash
 
-# ext4 in ubuntu is not supported
-ROOT_FS_TYPE=$(blkid -o udev $(df /boot/| awk '/dev/ {print $1}') | awk -F"=" '/ID_FS_TYPE=/ {print $2}')
+EXTLINUX=/usr/sbin/extlinux
+
+# ext4 in ubuntu is not supported by syslinux, use our extlinux-ext4
+ROOT_DEV=$(df /boot/| awk '/dev/ {print $1}')
+ROOT_FS_TYPE=$(blkid -o udev ${ROOT_DEV} | awk -F"=" '/ID_FS_TYPE=/ {print $2}')
+
 if [ "$ROOT_FS_TYPE" = "ext4" ]; then
-  echo "/etc/grub.d/50_extlinux: ERROR ext4 is not supported as root filesystem"
-  exit 0
+  if [ -x /usr/sbin/extlinux-ext4 ]; then
+    EXTLINUX=/usr/sbin/extlinux-ext4
+  else
+    echo "/etc/grub.d/50_extlinux: ERROR ext4 is not supported as root filesystem"
+    exit 0
+  fi
 fi
+
 
 
 VMLINUZ=$(readlink /vmlinuz)
 INITRD=$(readlink /initrd.img)
 
-echo "Updating extlinux..." >&2
+echo "Updating extlinux.conf ..." >&2
 
 mkdir -p /boot/extlinux
 
@@ -24,8 +33,17 @@ ontimeout max
 label max
 	menu label MAX
 	kernel /${VMLINUZ}
-	append initrd=/${INITRD} root=UUID=${GRUB_DEVICE_UUID} ro quiet splash
+	append initrd=/${INITRD} root=UUID=${GRUB_DEVICE_UUID} ro quiet splash acpi=force reboot=warn
 
 EOF
 
-extlinux -i /boot/extlinux
+echo "Running $EXTLINUX -i /boot/extlinux ..." >&2
+$EXTLINUX -i /boot/extlinux
+
+
+# check if installed ok
+if dd if=${ROOT_DEV} bs=512 count=1 2>/dev/null | grep -q SYSLINUX; then
+  echo "  Extlinux installed on ${ROOT_DEV}" >&2
+else
+  echo "  ERROR: Extlinux not found on ${ROOT_DEV}" >&2
+fi
