mario.izquierdo   * Fix user-setup-apply, add user to groups inside chroot   * Hide stepUserInfo   * Create alumno user from preseed data (see max-genlive preesed file)   * usr/lib/os-probes/mounted/35detect_max:     - Try to detect previous MaX using menu.lst of installed system   * ubiquity-maxui.desktop     - Add StartupNotification (busy mouse when launching)
git-svn-id: http://max.educa.madrid.org:8000/svn/trunk@155 424cea3e-0240-0410-9575-8bd47b58cd33

diff --git a/ubiquity-frontend-max/usr/share/dpsyco/skel/usr/lib/ubiquity/user-setup/user-setup-apply b/ubiquity-frontend-max/usr/share/dpsyco/skel/usr/lib/ubiquity/user-setup/user-setup-apply
--- a/ubiquity-frontend-max/usr/share/dpsyco/skel/usr/lib/ubiquity/user-setup/user-setup-apply
+++ b/ubiquity-frontend-max/usr/share/dpsyco/skel/usr/lib/ubiquity/user-setup/user-setup-apply
@@ -1,5 +1,6 @@
 #! /bin/bash
-set -e
+# MaX dont fail creating users
+#set -e
 
 . /usr/share/debconf/confmodule
 
@@ -194,13 +195,13 @@ fi
 # MaX add alumno user
 
 db_get passwd/alumno-username
-ALUMNO_USERNAME=$RET
+ALUMNO_USERNAME="$RET"
 
 db_get passwd/alumno-userfullname
-ALUMNO_USERFULLNAME=$RET
+ALUMNO_USERFULLNAME="$RET"
 
 db_get passwd/alumno-password
-ALUMNO_PASSWORD=$RET
+ALUMNO_PASSWORD="$RET"
 
 db_get passwd/alumno-default-groups
 ALUMNO_GROUPS=$RET
@@ -208,10 +209,10 @@ ALUMNO_GROUPS=$RET
 
 
 $log $chroot $ROOT adduser --disabled-password --gecos "$ALUMNO_USERFULLNAME" "$ALUMNO_USERNAME" >/dev/null || true
-setpassword "$ALUMNO_USERNAME" "$ALUMNO_PASSWORD" "false"
+setpassword "$ALUMNO_USERNAME" "$ALUMNO_PASSWORD" "false" || true
 
 for group in $ALUMNO_GROUPS; do
-  adduser alumno $group
+  $log $chroot $ROOT adduser $ALUMNO_USERNAME $group || true
 done
 
 exit 0
