ubiquity-frontend-max: (8.0.max1)
  * Sync with 2.18.8.7 of Ubuntu trusty

diff --git a/ubiquity-frontend-max/usr/share/grub-installer/grub-installer b/ubiquity-frontend-max/usr/share/grub-installer/grub-installer
--- a/ubiquity-frontend-max/usr/share/grub-installer/grub-installer
+++ b/ubiquity-frontend-max/usr/share/grub-installer/grub-installer
@@ -52,8 +52,19 @@ umount_on_exit () {
 	fi
 }
 
-if [ ! -e "$ROOT/proc/cmdline" ]; then
-	mount -t proc proc $ROOT/proc && umount_on_exit /proc
+# Ensure proc is mounted in all the $chroot calls;
+# needed for RAID+LVM for example
+initial_proc_contents="$(ls $ROOT/proc)"
+if [ -z "$initial_proc_contents" ]; then
+	info "Mounting /proc into $ROOT"
+	if [ "$(udpkg --print-os)" = "kfreebsd" ]; then
+		mount -t linprocfs proc $ROOT/proc && umount_on_exit /proc
+	else
+		mount -t proc proc $ROOT/proc && umount_on_exit /proc
+	fi
+fi
+
+if [ "$(udpkg --print-os)" = linux ] && [ -z "$(ls $ROOT/sys)" ]; then
 	mount -t sysfs sysfs $ROOT/sys && umount_on_exit /sys
 fi
 
@@ -159,7 +170,7 @@ hurd_convert () {
 # This should probably be rewritten using udevadm or similar.
 device_to_disk () {
 	echo "$1" | \
-		sed 's:\(/dev/\(cciss\|ida\|rs\)/c[0-9]d[0-9][0-9]*\|/dev/mmcblk[0-9]\|/dev/\(ad\|da\)[0-9]\+\|/dev/[hs]d[0-9]\+\|/dev/[a-z]\+\).*:\1:'
+		sed 's:\(/dev/\(cciss\|ida\|rs\)/c[0-9]d[0-9][0-9]*\|/dev/mmcblk[0-9]\|/dev/nvme[0-9]n[0-9]\|/dev/\(ad\|da\)[0-9]\+\|/dev/[hs]d[0-9]\+\|/dev/[a-z]\+\).*:\1:'
 }
 
 # Run update-grub in $ROOT
@@ -170,8 +181,8 @@ update_grub () {
 	else
 		in_target="log-output -t grub-installer $chroot $ROOT"
 	fi
-	if ! $in_target $update_grub; then
-		error "Running '$update_grub' failed." 1>&2
+	if ! $in_target $update_grub_cmd; then
+		error "Running '$update_grub_cmd' failed." 1>&2
 		db_input critical grub-installer/update-grub-failed || [ $? -eq 30 ]
 		db_go || true
 		db_progress STOP
@@ -313,7 +324,7 @@ case $prefix in
     /dev/loop)
 	disc_offered_devfs="$bootfs"
 	;;
-    /dev/[hsv]d[a-z0-9]|/dev/xvd[a-z]|/dev/cciss/c[0-9]d[0-9]*|/dev/ida/c[0-9]d[0-9]*|/dev/rs/c[0-9]d[0-9]*|/dev/mmcblk[0-9]|/dev/ad[0-9]*|/dev/da[0-9]*)
+    /dev/[hsv]d[a-z0-9]|/dev/xvd[a-z]|/dev/cciss/c[0-9]d[0-9]*|/dev/ida/c[0-9]d[0-9]*|/dev/rs/c[0-9]d[0-9]*|/dev/mmcblk[0-9]|/dev/ad[0-9]*|/dev/da[0-9]*|/dev/fio[a-z]|/dev/nvme[0-9]n[0-9])
 	disc_offered_devfs="$prefix"
 	;;
     *)
@@ -404,15 +415,25 @@ fi
 
 info "Identified partition label for $bootfs: $bootfslabel"
 
+experimental_arch () {
+	db_subst grub-installer/grub_not_mature_on_this_platform ARCH $ARCH
+	db_input low grub-installer/grub_not_mature_on_this_platform || [ $? -eq 30 ]
+	db_go || exit 10
+	db_get grub-installer/grub_not_mature_on_this_platform
+	if [ "$RET" != true ]; then
+		exit 10
+	fi
+}
+
 case $ARCH in
     i386/mac|amd64/mac)
 	# Note: depends on partman-efi to load the efivars module!
 	if [ -d /sys/firmware/efi ]; then
 		# This point can't be reached (yet).  See debian/isinstallable.
 		grub_package="grub-efi"
+		experimental_arch
 	else
-		# On PC/BIOS, default to GRUB Legacy
-		grub_package="grub"
+		grub_package="grub-pc"
 	fi
 	;;
     i386/efi|amd64/efi)
@@ -421,60 +442,37 @@ case $ARCH in
 	else
 		grub_package="grub-efi"
 	fi
-	;;
-    i386/*|amd64/*)
-	# On PC/BIOS, default to GRUB Legacy
-	grub_package="grub"
-	;;
-    kfreebsd-i386/*|kfreebsd-amd64/*)
-	grub_package="grub-pc"
-	;;
-    hurd-i386/*)
-	grub_package="grub-pc"
+	if [ ! -d /target/boot/efi ]; then
+		# No EFI System Partition, so presumably the partitioner
+		# believed this to be unnecessary, perhaps because we're
+		# installing on a pre-existing MBR partition table or
+		# perhaps because there's a BIOS Boot Partition.  In either
+		# case, the right answer is to fall back to grub-pc.
+		grub_package="grub-pc"
+	fi
 	;;
     powerpc/*)
+	grub_package="grub-ieee1275"
+	experimental_arch
+	;;
+    ppc64el/*)
 	grub_package="grub-ieee1275"
 	;;
     mipsel/loongson-2f)
 	grub_package="grub-yeeloong"
 	;;
     *)
-	info "Unknown architecture $ARCH, defaulting to grub-legacy"
-	grub_package="grub"
+	grub_package="grub-pc"
 esac
 
 case "$frtype:$bootfstype:$bootfslabel:$grub_package" in
-    lvm:*:*:*)
-	# Booting from LVM requires grub2
-	grub_package="grub-pc"
+    *:*:*:grub-yeeloong | lvm:*:*:* | *:*:gpt:* | *:ufs:*:* | *:zfs:*:* | *:btrfs:*:* )
+	# grub-legacy is not an option in these configurations
 	;;
-    *:*:*:grub)
+    *:*:*:grub-pc)
 	db_get grub-installer/grub2_instead_of_grub_legacy
-	if [ "$RET" = true ]; then
-		grub_package="grub-pc"
-	fi
-	;;
-    *:ufs:*:*)
-	# Booting from UFS requires grub2
-	grub_package="grub-pc"
-	;;
-    *:zfs:*:*)
-	# Booting from ZFS requires grub2
-	grub_package="grub-pc"
-	;;
-    *:ext2fs:*:grub-pc | *:xfs:*:grub-pc)
-    	# Booting ext2fs or xfs using grub2 works
-        ;;
-    *:*:*:grub-efi* | *:*:*:grub-yeeloong)
-	# No reasonable alternative to GRUB here
-	;;
-    *:*:*:*)
-	db_subst grub-installer/grub_not_mature_on_this_platform ARCH $ARCH
-	db_input low grub-installer/grub_not_mature_on_this_platform || [ $? -eq 30 ]
-	db_go || exit 10
-	db_get grub-installer/grub_not_mature_on_this_platform
-	if [ "$RET" != true ]; then
-		exit 10
+	if [ "$RET" = false ]; then
+		grub_package="grub"
 	fi
 	;;
 esac
@@ -483,14 +481,14 @@ case $grub_package in
     grub)
 	grub_version="grub"
 	menu_file="menu.lst"
-	update_grub="update-grub -y"
+	update_grub_cmd="update-grub -y"
 	partition_offset=1
 	frgrubroot=$(($frgrubroot - 1))
 	;;
     *)
 	grub_version="grub2"
 	menu_file="grub.cfg"
-	update_grub="update-grub"
+	update_grub_cmd="update-grub"
 	partition_offset=0
 	;;
 esac
@@ -528,28 +526,9 @@ if [ "$got_splash" ] && \
    (! db_get debian-installer/splash || [ "$RET" = true ]); then
 	defopt_params=${defopt_params:+$defopt_params }splash
 fi
-if [ "$grub_version" = grub2 ]; then
-	# Add user parameters to the menu file; some options are only added
-	# to the default entry for a kernel instead of all entries.
-	# We have to duplicate grub2's default for
-	# GRUB_CMDLINE_LINUX_DEFAULT here.
-	if [ -z "$got_splash" ] && \
-	   db_get debian-installer/framebuffer && [ "$RET" = true ] && \
-	   (! db_get debian-installer/splash || [ "$RET" = true ]); then
-		defopt_params="splash${defopt_params:+ $defopt_params}"
-	fi
-	if [ -z "$got_quiet" ] && \
-	   (! db_get debian-installer/quiet || [ "$RET" = true ]); then
-		defopt_params="quiet${defopt_params:+ $defopt_params}"
-	fi
-	# (quoting to deconfuse vim)
-	$chroot $ROOT 'debconf-set-selections' <<EOF
-$grub_package grub2/linux_cmdline string $kopt_params
-$grub_package grub2/linux_cmdline_default string $defopt_params
-EOF
-fi
 if [ "$grub_package" = grub-pc ]; then
 	# Empty this for now to stop it being asked. We'll fix this up later.
+	# (quoting to deconfuse vim)
 	$chroot $ROOT 'debconf-set-selections' <<EOF
 $grub_package grub-pc/install_devices multiselect
 $grub_package grub-pc/install_devices_empty boolean true
@@ -620,7 +599,6 @@ os-prober > /tmp/os-probed || true
 db_settitle debian-installer/grub-installer/title
 
 # Work out what probed OSes can be booted from grub
-tmpfile=/tmp/menu.lst.extras
 if [ -s /tmp/os-probed ]; then
 	supported_os_list=""
 	unsupported_os_list=""
@@ -699,6 +677,9 @@ fi
 default_bootdev_os="$($chroot $ROOT grub-mkdevicemap --no-floppy -m - | head -n1 | cut -f2)"
 if [ "$default_bootdev_os" ]; then
 	default_bootdev="$($chroot $ROOT readlink -f "$default_bootdev_os")"
+	if db_get grub-installer/bootdev && [ "$RET" = '(hd0)' ]; then
+		db_set grub-installer/bootdev "$default_bootdev"
+	fi
 else
 	default_bootdev="(hd0)"
 fi
@@ -748,7 +729,7 @@ case $ARCH:$grub_package in
 			  sed 's:\(/dev/\(cciss\|ida\|rs\)/c[0-9]d[0-9][0-9]*\|/dev/mmcblk[0-9]\|/dev/\(ad\|da\)[0-9]\+\|/dev/[a-z]\+\).*:\1:')
 			disks="${disks:+$disks }$prefix"
 			case $prefix in
-			    /dev/[hsv]d[a-z]|/dev/xvd[a-z]|/dev/cciss/c[0-9]d[0-9]*|/dev/ida/c[0-9]d[0-9]*|/dev/rs/c[0-9]d[0-9]*|/dev/mmcblk[0-9]|/dev/ad[0-9]*|/dev/da[0-9]*)
+			    /dev/[hsv]d[a-z]|/dev/xvd[a-z]|/dev/cciss/c[0-9]d[0-9]*|/dev/ida/c[0-9]d[0-9]*|/dev/rs/c[0-9]d[0-9]*|/dev/mmcblk[0-9]|/dev/ad[0-9]*|/dev/da[0-9]*|/dev/fio[a-z]|/dev/nvme[0-9]n[0-9])
 				if [ "$prefix" != "$frdisk_one" ]; then
 					use_disks=1
 				fi
@@ -766,6 +747,10 @@ case $ARCH:$grub_package in
 		db_set grub-installer/bootdev "$default_bootdev"
 	fi
 	;;
+    ppc64el/*:grub-ieee1275)
+	bootdev="$(/usr/lib/grub-installer/prep-bootdev)"
+	state=3
+	;;
     *)
 	# No need for install device selection on other platforms.
 	bootdev=dummy
@@ -777,7 +762,11 @@ db_progress STEP 1
 db_progress INFO grub-installer/progress/step_bootdev
 
 while : ; do
-	if [ "$state" = 1 ]; then
+	db_fget grub-installer/bootdev seen
+	if [ "$RET" = true ] && db_get grub-installer/bootdev && [ "$RET" ] ; then
+		bootdev=$RET
+		break
+	elif [ "$state" = 1 ]; then
 		if [ "$frdev" ]; then
 			# If /boot is on SATA RAID/multipath, then there's
 			# only one possible answer; we don't support device
@@ -839,12 +828,6 @@ while : ; do
 	fi
 done
 
-if [ "$grub_version" = grub ] && [ ! -f "$device_map" ] && \
-   db_get grub-installer/bootdev_directory && [ "$RET" ]; then
-	bootdev=
-	echo quit | $chroot $ROOT /usr/sbin/grub --batch --device-map="${device_map#$ROOT}" >/dev/null 2>&1
-fi
-
 db_progress STEP 1
 db_subst grub-installer/progress/step_install_loader BOOTDEV "$bootdev"
 db_progress INFO grub-installer/progress/step_install_loader
@@ -902,9 +885,16 @@ if [ -z "$frdisk" ] || [ "$grub_version" = grub2 ]; then
 			grub_install_params="$grub_install_params --force"
 		fi
 
+		case $ARCH:$grub_package in
+		    ppc64el/*:grub-ieee1275)
+			info "Wiping PReP partition $bootdev"
+			log-output -t grub-installer dd if=/dev/zero of="$bootdev" bs=512 count="$(blockdev --getsz "$bootdev")"
+			;;
+		esac
+
 		CODE=0
 		case $ARCH:$grub_package in
-		    *:grub|*:grub-pc|sparc:grub-ieee1275)
+		    *:grub|*:grub-pc|sparc:grub-ieee1275|ppc64el/*:grub-ieee1275)
 			info "Running $chroot $ROOT grub-install $grub_install_params \"$bootdev\""
 			log-output -t grub-installer $chroot $ROOT grub-install $grub_install_params "$bootdev" || CODE=$?
 			;;
@@ -915,16 +905,15 @@ if [ -z "$frdisk" ] || [ "$grub_version" = grub2 ]; then
 		esac
 		if [ "$CODE" = 0 ]; then
 			info "grub-install ran successfully"
-                       if [ ! -d /sys/firmware/efi ] && [ -e /tmp/max_sti ]; then
-                               info "DETECTED STI card running $chroot $ROOT grub-install $grub_install_params \"/dev/sda1\""
-                               log-output -t grub-installer $chroot $ROOT grub-install $grub_install_params "/dev/sda1"
-                               rm -f /tmp/max_sti
-                       fi
-
-
+                        # MAX
+                        if [ ! -d /sys/firmware/efi ] && [ -e /tmp/max_sti ]; then
+                            info "DETECTED STI card running $chroot $ROOT grub-install $grub_install_params \"/dev/sda1\""
+                            log-output -t grub-installer $chroot $ROOT grub-install $grub_install_params "/dev/sda1"
+                            rm -f /tmp/max_sti
+                        fi
 		else
 			case $ARCH:$grub_package in
-			    *:grub|*:grub-pc|sparc:grub-ieee1275)
+			    *:grub|*:grub-pc|sparc:grub-ieee1275|ppc64el/*:grub-ieee1275)
 				error "Running 'grub-install $grub_install_params \"$bootdev\"' failed."
 				;;
 			    *)
@@ -980,7 +969,7 @@ split_device () {
 	disk=
 	part=
 	case $1 in
-		/dev/[vhs]d[a-z]*)
+		/dev/[vhs]d[a-z]*|/dev/fio[a-z]*)
 			disk="$(echo "$1" | sed 's,\(/dev/[a-z]\+\).*,\1,')"
 			part="$(echo "$1" | sed 's,/dev/[a-z]\+\(.*\),\1,')"
 			;;
@@ -992,6 +981,11 @@ split_device () {
 		/dev/mmcblk*)
 			disk="$(echo "$1" | sed 's,\(/dev/mmcblk[0-9]\+\).*,\1,')"
 			part="$(echo "$1" | sed 's,/dev/mmcblk[0-9]\+p\([0-9]\+\),\1,')"
+			[ "$part" != "$1" ] || part=
+			;;
+		/dev/nvme*n*)
+			disk="$(echo "$1" | sed 's,\(/dev/nvme[0-9]\+n[0-9]\+\).*,\1,')"
+			part="$(echo "$1" | sed 's,/dev/nvme[0-9]\+n[0-9]\+p\([0-9]\+\),\1,')"
 			[ "$part" != "$1" ] || part=
 			;;
 	esac
@@ -1092,9 +1086,9 @@ db_progress STEP 1
 db_progress INFO grub-installer/progress/step_config_loader
 
 if [ "$bootfstype" = "zfs" ]; then
-  # Required by update-grub on ZFS
-  mkdir -p $ROOT/boot/zfs
-  cp /boot/zfs/zpool.cache $ROOT/boot/zfs/
+	# Required by update-grub on ZFS
+	mkdir -p $ROOT/boot/zfs
+	cp /boot/zfs/zpool.cache $ROOT/boot/zfs/
 fi
 
 # Delete for idempotency
@@ -1184,20 +1178,9 @@ if [ "$grub_version" = "grub" ] ; then
 	fi 
 fi
 
-bootdev_directory=""
-hide_menu=""
-if db_get grub-installer/bootdev_directory && [ "$RET" ]; then
-	bootdev_directory="$RET"
-	# Be careful to deal with either UUID-style or non-UUID-style groot.
-	# grub4dos doesn't recognise UUIDs yet.
-	sed -i "s:^\(# groot=\)[^(].*:\1():; s:^\(# groot=([^)]*)\).*:\1$bootdev_directory:" $ROOT/boot/grub/$menu_file
-	hide_menu=1
-fi
+# Add user parameters to menu.lst; some options are only added to the
+# default entry for a kernel instead of all entries.
 if [ "$grub_version" = grub ]; then
-	# Add user parameters to menu.lst; some options are only added to
-	# the default entry for a kernel instead of all entries. We can't do
-	# this in the same place as the grub2 case because we need the menu
-	# file to exist.
 	if db_get debian-installer/splash && [ "$RET" = false ]; then
 		sed -i 's!^\(# defoptions=.*\) splash\( \|$\)!\1\2!' $ROOT/boot/grub/$menu_file
 	fi
@@ -1207,10 +1190,38 @@ if [ "$grub_version" = grub ]; then
 	if [ "$kopt_params" ]; then
 		sed -i "s!^\(# kopt=.*\)!\1 $kopt_params!" $ROOT/boot/grub/$menu_file
 	fi
-	# In either case, update the Debian kernel entries
-	if [ "$user_params" ] || [ "$bootdev_directory" ]; then
-		update_grub
+else
+	# It's simplest to duplicate grub2's default for
+	# GRUB_CMDLINE_LINUX_DEFAULT here, as well as its handling of
+	# quoting.
+	set_config_item () {
+		local key value
+		key="$1"
+		value="$(echo "$2" | sed -e 's,[$`"\],\\&,g')"
+		if grep -q "^$key=" "$ROOT/etc/default/grub"; then
+			value="$(echo "$value" | sed -e 's,[\@],\\&,g')"
+			sed -i -re "s@^($key=).*@\1\"$value\"@" "$ROOT/etc/default/grub"
+		else
+			echo >> "$ROOT/etc/default/grub"
+			echo "$key=\"$value\"" >> "$ROOT/etc/default/grub"
+		fi
+	}
+
+	if [ -z "$got_splash" ] && \
+	   db_get debian-installer/framebuffer && [ "$RET" = true ] && \
+	   (! db_get debian-installer/splash || [ "$RET" = true ]); then
+		defopt_params="splash${defopt_params:+ $defopt_params}"
 	fi
+	if [ -z "$got_quiet" ] && \
+	   (! db_get debian-installer/quiet || [ "$RET" = true ]); then
+		defopt_params="quiet${defopt_params:+ $defopt_params}"
+	fi
+	set_config_item GRUB_CMDLINE_LINUX_DEFAULT "$defopt_params"
+	set_config_item GRUB_CMDLINE_LINUX "$kopt_params"
+fi
+# In either case, update the Debian kernel entries
+if [ "$user_params" ]; then
+	update_grub
 fi
 
 if db_get grub-installer/timeout
@@ -1222,7 +1233,7 @@ then
 	fi
 fi
 
-if [ -z "$hide_menu" ] && [ -s /tmp/os-probed ]; then
+if [ -s /tmp/os-probed ]; then
 	# Other operating systems are installed, so show the menu by default
 	# and raise the timeout.
 	if [ "$grub_version" = grub ]; then
