max-skel-conf (6.0.max6)   * Add XDG default config in /etc/skel
git-svn-id: http://max.educa.madrid.org:8000/svn/trunk@765 424cea3e-0240-0410-9575-8bd47b58cd33

diff --git a/max-skel-conf/debian/rules b/max-skel-conf/debian/rules
--- a/max-skel-conf/debian/rules
+++ b/max-skel-conf/debian/rules
@@ -5,11 +5,16 @@ include /usr/share/cdbs/1/rules/debhelper.mk
 binary-install/max-skel-conf::
 	# clean svn dirs
 	@find $(CURDIR)/debian/max-skel-conf -type d -name .svn | xargs rm -rf --
-	@rm -rf $(CURDIR)/debian/max-skel-conf/usr/share/dpsyco/skel/etc/skel/.kde
-	@for dir in `find $(CURDIR)/debian/max-skel-conf/usr -type d| grep -v "qdvdauthor"`; do \
-		(rmdir --ignore-fail-on-non-empty $$dir || true); \
+
+#	rm -rf $(CURDIR)/debian/max-skel-conf/usr/share/dpsyco/skel/etc/skel/.kde
+#	rm -rf $(CURDIR)/debian/max-skel-conf/usr/share/dpsyco/skel/etc/skel/.local
+
+	@for dir in `find $(CURDIR)/debian/max-skel-conf/usr -type d`; do \
+                echo "   TRY TO DELETE: $$dir"; \
+#		(rmdir -p --ignore-fail-on-non-empty "$$dir" || true); \
+		rmdir -p --ignore-fail-on-non-empty "$$dir"; \
                 ([ ! -d "$$dir" ] && echo "   EMPTY DELETED: $$dir"); \
-	done
+	done || true
 
 binary-install/homealumno::
 	# clean svn dirs
